# apis.py (Structure for Website Backend)
APIS = {
    "sms": [
        {"name": "Flipkart SMS", "url": "https://www.flipkart.com/api/5/user/otp/generate", "method": "POST", "type": "sms"},
        {"name": "Amazon SMS", "url": "https://www.amazon.in/ap/signin", "method": "POST", "type": "sms"},
        {"name": "Zomato SMS", "url": "https://www.zomato.com/php/social_login.php", "method": "POST", "type": "sms"},
        {"name": "Swiggy SMS", "url": "https://www.swiggy.com/api/auth/otp", "method": "POST", "type": "sms"},
        {"name": "Meesho SMS", "url": "https://api.meesho.com/auth/v2/login/mobile", "method": "POST", "type": "sms"},
        {"name": "Shopsy SMS", "url": "https://api.shopsy.in/auth/v1/login/otp", "method": "POST", "type": "sms"},
        {"name": "Myntra SMS", "url": "https://www.myntra.com/register/send_otp", "method": "POST", "type": "sms"},
        {"name": "Ajio SMS", "url": "https://login.web.ajio.com/api/auth/signupSendOTP", "method": "POST", "type": "sms"},
        {"name": "1mg SMS", "url": "https://api.1mg.com/auth/v1/mobile/otp", "method": "POST", "type": "sms"},
        {"name": "Pharmeasy SMS", "url": "https://pharmeasy.in/api/auth/requestOTP", "method": "POST", "type": "sms"},
        {"name": "Practo SMS", "url": "https://accounts.practo.com/send_otp", "method": "POST", "type": "sms"},
        {"name": "Apollo Pharmacy", "url": "https://www.apollopharmacy.in/sociallogin/mobile/sendotp/", "method": "POST", "type": "sms"},
        {"name": "Byju's SMS", "url": "https://bcas-prod.byjusweb.com/api/send-otp", "method": "POST", "type": "sms"},
        {"name": "Unacademy SMS", "url": "https://unacademy.com/api/v3/user/user_check/", "method": "POST", "type": "sms"},
        {"name": "Vedantu SMS", "url": "https://user.vedantu.com/user/preLoginVerification", "method": "POST", "type": "sms"},
        {"name": "Cuemath SMS", "url": "https://www.cuemath.com/api/v4/parents/", "method": "POST", "type": "sms"},
        {"name": "Khan Academy", "url": "https://www.khanacademy.org/api/internal/auth/send_verification_email", "method": "POST", "type": "sms"},
        {"name": "Netflix SMS", "url": "https://www.netflix.com/api/register", "method": "POST", "type": "sms"},
        {"name": "Google Pay", "url": "https://pay.google.com/gp/p/v1/request/otp", "method": "POST", "type": "sms"},
        {"name": "PhonePe SMS", "url": "https://api.phonepe.com/apis/hermes/sendotp", "method": "POST", "type": "sms"},
        {"name": "Mobikwik SMS", "url": "https://api.mobikwik.com/v2/user/login/send_otp", "method": "POST", "type": "sms"},
        {"name": "CRED SMS", "url": "https://api.cred.club/api/v1/users/otp", "method": "POST", "type": "sms"},
        {"name": "Paytm SMS", "url": "https://accounts.paytm.com/api/sendotp", "method": "POST", "type": "sms"},
        {"name": "Cleartrip SMS", "url": "https://www.cleartrip.com/api/v1/users/otp/send", "method": "POST", "type": "sms"},
        {"name": "Yatra SMS", "url": "https://www.yatra.com/booking/generate-otp", "method": "POST", "type": "sms"},
        {"name": "Goibibo SMS", "url": "https://www.goibibo.com/common/downloadsms/", "method": "GET", "type": "sms"},
        {"name": "MakeMyTrip SMS", "url": "https://mapi.makemytrip.com/ext/web/pwa/isUserRegistered", "method": "GET", "type": "sms"},
        {"name": "UrbanClap SMS", "url": "https://www.urbanclap.com/api/v2/growth/profile/generateOTP", "method": "POST", "type": "sms"},
        {"name": "BigBasket SMS", "url": "https://www.bigbasket.com/api/login/generate-otp/", "method": "POST", "type": "sms"},
        {"name": "Grofers SMS", "url": "https://grofers.com/v2/accounts/", "method": "POST", "type": "sms"},
        {"name": "Dream11 SMS", "url": "https://www.dream11.com/graphql/mutation/pwa/register", "method": "POST", "type": "sms"},
        {"name": "MPan SMS", "url": "https://mpan.in/api/otp/send", "method": "POST", "type": "sms"},
        {"name": "Hotstar SMS", "url": "https://api.hotstar.com/um/v3/users/register", "method": "POST", "type": "sms"},
        {"name": "AltBalaji SMS", "url": "https://api.cloud.altbalaji.com/accounts/mobile/verify?domain=IN", "method": "POST", "type": "sms"},
        {"name": "Voot SMS", "url": "https://us-central1-vootdev.cloudfunctions.net/usersV3/v3/checkUser", "method": "POST", "type": "sms"},
        {"name": "SonyLiv SMS", "url": "https://apiv2.sonyliv.com/AGL/1.6/A/ENG/WEB/IN/CREATEOTP", "method": "POST", "type": "sms"},
        {"name": "MXPlayer SMS", "url": "https://api.mxplayer.in/v2/user/login", "method": "POST", "type": "sms"},
        {"name": "JioCinema SMS", "url": "https://auth.jiocinema.com/v2/user/login", "method": "POST", "type": "sms"},
    ],
    "call": [
        {"name": "Tata Capital Call", "url": "https://mobapp.tatacapital.com/DLPDelegator/authentication/mobile/v0.1/sendOtpOnVoice", "method": "POST", "type": "call"},
        {"name": "1mg Call", "url": "https://www.1mg.com/auth_api/v6/create_token", "method": "POST", "type": "call"},
        {"name": "Swiggy Call", "url": "https://profile.swiggy.com/api/v3/app/request_call_verification", "method": "POST", "type": "call"},
        {"name": "Myntra Call", "url": "https://www.myntra.com/gw/mobile-auth/voice-otp", "method": "POST", "type": "call"},
        {"name": "Flipkart Call", "url": "https://www.flipkart.com/api/6/user/voice-otp/generate", "method": "POST", "type": "call"},
        {"name": "Amazon Call", "url": "https://www.amazon.in/ap/signin", "method": "POST", "type": "call"},
        {"name": "Paytm Call", "url": "https://accounts.paytm.com/signin/voice-otp", "method": "POST", "type": "call"},
        {"name": "Zomato Call", "url": "https://www.zomato.com/php/o2_api_handler.php", "method": "POST", "type": "call"},
        {"name": "MakeMyTrip Call", "url": "https://www.makemytrip.com/api/4/voice-otp/generate", "method": "POST", "type": "call"},
        {"name": "Goibibo Call", "url": "https://www.goibibo.com/user/voice-otp/generate/", "method": "POST", "type": "call"},
        {"name": "Ola Call", "url": "https://api.olacabs.com/v1/voice-otp", "method": "POST", "type": "call"},
        {"name": "Uber Call", "url": "https://auth.uber.com/v2/voice-otp", "method": "POST", "type": "call"},
        {"name": "Foxy WhatsApp", "url": "https://www.foxy.in/api/v2/users/send_otp", "method": "POST", "type": "call"},
        {"name": "Stratzy WhatsApp", "url": "https://stratzy.in/api/web/whatsapp/sendOTP", "method": "POST", "type": "call"},
        {"name": "Rappi WhatsApp", "url": "https://services.mxgrability.rappi.com/api/rappi-authentication/login/whatsapp/create", "method": "POST", "type": "call"},
        {"name": "Eka Care WhatsApp", "url": "https://auth.eka.care/auth/init", "method": "POST", "type": "call"},
        {"name": "KPN Fresh", "url": "https://api.kpnfresh.com/s/authn/api/v1/otp-generate", "method": "POST", "type": "call"},
        {"name": "Lenskart Call", "url": "https://api-gateway.juno.lenskart.com/v3/customers/sendOtp", "method": "POST", "type": "call"},
        {"name": "NoBroker Call", "url": "https://www.nobroker.in/api/v3/account/otp/send", "method": "POST", "type": "call"},
        {"name": "PharmEasy Call", "url": "https://pharmeasy.in/api/v2/auth/send-otp", "method": "POST", "type": "call"},
        {"name": "Wakefit Call", "url": "https://api.wakefit.co/api/consumer-sms-otp/", "method": "POST", "type": "call"},
        {"name": "Byjus Call", "url": "https://api.byjus.com/v2/otp/send", "method": "POST", "type": "call"},
        {"name": "Hungama Call", "url": "https://communication.api.hungama.com/v1/communication/otp", "method": "POST", "type": "call"},
        {"name": "Meru Cab", "url": "https://merucabapp.com/api/otp/generate", "method": "POST", "type": "call"},
        {"name": "Doubtnut Call", "url": "https://api.doubtnut.com/v4/student/login", "method": "POST", "type": "call"},
        {"name": "PenPencil Call", "url": "https://api.penpencil.co/v1/users/resend-otp?smsType=1", "method": "POST", "type": "call"},
        {"name": "Snitch Call", "url": "https://mxemjhp3rt.ap-south-1.awsapprunner.com/auth/otps/v2", "method": "POST", "type": "call"},
        {"name": "Dayco India", "url": "https://ekyc.daycoindia.com/api/nscript_functions.php", "method": "POST", "type": "call"},
        {"name": "BeepKart", "url": "https://api.beepkart.com/buyer/api/v2/public/leads/buyer/otp", "method": "POST", "type": "call"},
        {"name": "Lending Plate", "url": "https://lendingplate.com/api.php", "method": "POST", "type": "call"},
        {"name": "ShipRocket", "url": "https://sr-wave-api.shiprocket.in/v1/customer/auth/otp/send", "method": "POST", "type": "call"},
        {"name": "GoKwik", "url": "https://gkx.gokwik.co/v3/gkstrict/auth/otp/send", "method": "POST", "type": "call"},
        {"name": "NewMe", "url": "https://prodapi.newme.asia/web/otp/request", "method": "POST", "type": "call"},
        {"name": "Univest", "url": "https://api.univest.in/api/auth/send-otp", "method": "POST", "type": "call"},
        {"name": "Smytten", "url": "https://route.smytten.com/discover_user/NewDeviceDetails/addNewOtpCode", "method": "POST", "type": "call"},
        {"name": "CaratLane", "url": "https://www.caratlane.com/cg/dhevudu", "method": "POST", "type": "call"},
        {"name": "BikeFixup", "url": "https://api.bikefixup.com/api/v2/send-registration-otp", "method": "POST", "type": "call"},
        {"name": "WellAcademy", "url": "https://wellacademy.in/store/api/numberLoginV2", "method": "POST", "type": "call"},
        {"name": "ServeTel", "url": "https://api.servetel.in/v1/auth/otp", "method": "POST", "type": "call"},
        {"name": "GoPink Cabs", "url": "https://www.gopinkcabs.com/app/cab/customer/login_admin_code.php", "method": "POST", "type": "call"},
        {"name": "Shemaroome", "url": "https://www.shemaroome.com/users/resend_otp", "method": "POST", "type": "call"},
        {"name": "Cossouq", "url": "https://www.cossouq.com/mobilelogin/otp/send", "method": "POST", "type": "call"},
        {"name": "MyImagineStore", "url": "https://www.myimaginestore.com/mobilelogin/index/registrationotpsend/", "method": "POST", "type": "call"},
        {"name": "Otpless", "url": "https://user-auth.otpless.app/v2/lp/user/transaction/intent/e51c5ec2-6582-4ad8-aef5-dde7ea54f6a3", "method": "POST", "type": "call"},
        {"name": "MyHubble Money", "url": "https://api.myhubble.money/v1/auth/otp/generate", "method": "POST", "type": "call"},
        {"name": "Tata Capital Business", "url": "https://businessloan.tatacapital.com/CLIPServices/otp/services/generateOtp", "method": "POST", "type": "call"},
        {"name": "DealShare", "url": "https://services.dealshare.in/userservice/api/v1/user-login/send-login-code", "method": "POST", "type": "call"},
        {"name": "Snapmint", "url": "https://api.snapmint.com/v1/public/sign_up", "method": "POST", "type": "call"},
        {"name": "Housing.com", "url": "https://login.housing.com/api/v2/send-otp", "method": "POST", "type": "call"},
        {"name": "RentoMojo", "url": "https://www.rentomojo.com/api/RMUsers/isNumberRegistered", "method": "POST", "type": "call"},
        {"name": "Khatabook", "url": "https://api.khatabook.com/v1/auth/request-otp", "method": "POST", "type": "call"},
        {"name": "Netmeds", "url": "https://apiv2.netmeds.com/mst/rest/v1/id/details/", "method": "POST", "type": "call"},
        {"name": "Nykaa", "url": "https://www.nykaa.com/app-api/index.php/customer/send_otp", "method": "POST", "type": "call"},
        {"name": "RummyCircle", "url": "https://www.rummycircle.com/api/fl/auth/v3/getOtp", "method": "POST", "type": "call"},
        {"name": "Animall", "url": "https://animall.in/zap/auth/login", "method": "POST", "type": "call"},
        {"name": "PenPencil V3", "url": "https://xylem-api.penpencil.co/v1/users/register/64254d66be2a390018e6d348", "method": "POST", "type": "call"},
        {"name": "Entri", "url": "https://entri.app/api/v3/users/check-phone/", "method": "POST", "type": "call"},
        {"name": "Cosmofeed", "url": "https://prod.api.cosmofeed.com/api/user/authenticate", "method": "POST", "type": "call"},
        {"name": "Aakash", "url": "https://antheapi.aakash.ac.in/api/generate-lead-otp", "method": "POST", "type": "call"},
        {"name": "Revv", "url": "https://st-core-admin.revv.co.in/stCore/api/customer/v1/init", "method": "POST", "type": "call"},
        {"name": "DeHaat", "url": "https://oidc.agrevolution.in/auth/realms/dehaat/custom/sendOTP", "method": "POST", "type": "call"},
        {"name": "A23 Games", "url": "https://pfapi.a23games.in/a23user/signup_by_mobile_otp/v2", "method": "POST", "type": "call"},
        {"name": "Spencer's", "url": "https://jiffy.spencers.in/user/auth/otp/send", "method": "POST", "type": "call"},
        {"name": "PayMe India", "url": "https://api.paymeindia.in/api/v2/authentication/phone_no_verify/", "method": "POST", "type": "call"},
        {"name": "Shopper's Stop", "url": "https://www.shoppersstop.com/services/v2_1/ssl/sendOTP/OB", "method": "POST", "type": "call"},
        {"name": "Hyuga Auth", "url": "https://hyuga-auth-service.pratech.live/v1/auth/otp/generate", "method": "POST", "type": "call"},
        {"name": "BigCash", "url": "https://www.bigcash.live/sendsms.php", "method": "POST", "type": "call"},
        {"name": "Lifestyle Stores", "url": "https://www.lifestylestores.com/in/en/mobilelogin/sendOTP", "method": "POST", "type": "call"},
        {"name": "WorkIndia", "url": "https://api.workindia.in/api/candidate/profile/login/verify-number/", "method": "POST", "type": "call"},
        {"name": "PokerBaazi", "url": "https://nxtgenapi.pokerbaazi.com/oauth/user/send-otp", "method": "POST", "type": "call"},
        {"name": "My11Circle", "url": "https://www.my11circle.com/api/fl/auth/v3/getOtp", "method": "POST", "type": "call"},
        {"name": "MamaEarth", "url": "https://auth.mamaearth.in/v1/auth/initiate-signup", "method": "POST", "type": "call"},
        {"name": "HomeTriangle", "url": "https://hometriangle.com/api/partner/xauth/signup/otp", "method": "POST", "type": "call"},
        {"name": "Wellness Forever", "url": "https://paalam.wellnessforever.in/crm/v2/firstRegisterCustomer", "method": "POST", "type": "call"},
        {"name": "HealthMug", "url": "https://api.healthmug.com/account/createotp", "method": "POST", "type": "call"},
        {"name": "Vyapar", "url": "https://vyaparapp.in/api/ftu/v3/send/otp", "method": "POST", "type": "call"},
        {"name": "Kredily", "url": "https://app.kredily.com/ws/v1/accounts/send-otp/", "method": "POST", "type": "call"},
        {"name": "Tata Motors", "url": "https://cars.tatamotors.com/content/tml/pv/in/en/account/login.signUpMobile.json", "method": "POST", "type": "call"},
        {"name": "Moglix", "url": "https://apinew.moglix.com/nodeApi/v1/login/sendOTP", "method": "POST", "type": "call"},
        {"name": "MyGov", "url": "https://auth.mygov.in/regapi/register_api_ver1/", "method": "POST", "type": "call"},
        {"name": "TrulyMadly", "url": "https://app.trulymadly.com/api/auth/mobile/v1/send-otp", "method": "POST", "type": "call"},
        {"name": "Apna", "url": "https://production.apna.co/api/userprofile/v1/otp/", "method": "POST", "type": "call"},
        {"name": "CodFirm", "url": "https://api.codfirm.in/api/customers/login/otp", "method": "POST", "type": "call"},
        {"name": "Swipe", "url": "https://app.getswipe.in/api/user/mobile_login", "method": "POST", "type": "call"},
        {"name": "More Retail", "url": "https://omni-api.moreretail.in/api/v1/login/", "method": "POST", "type": "call"},
        {"name": "Country Delight", "url": "https://api.countrydelight.in/api/v1/customer/requestOtp", "method": "POST", "type": "call"},
        {"name": "AstroSage", "url": "https://vartaapi.astrosage.com/sdk/registerAS", "method": "POST", "type": "call"},
        {"name": "Rapido", "url": "https://customer.rapido.bike/api/otp", "method": "POST", "type": "call"},
        {"name": "TooToo", "url": "https://tootoo.in/graphql", "method": "POST", "type": "call"},
        {"name": "ConfirmTkt", "url": "https://securedapi.confirmtkt.com/api/platform/registerOutput", "method": "POST", "type": "call"},
        {"name": "BetterHalf", "url": "https://api.betterhalf.ai/v2/auth/otp/send/", "method": "POST", "type": "call"},
        {"name": "Charzer", "url": "https://api.charzer.com/auth-service/send-otp", "method": "POST", "type": "call"},
        {"name": "Nuvama Wealth", "url": "https://nma.nuvamawealth.com/edelmw-content/content/otp/register", "method": "POST", "type": "call"},
        {"name": "Mpokket", "url": "https://web-api.mpokket.in/registration/sendOtp", "method": "POST", "type": "call"},
        {"name": "Breeze Session", "url": "https://api.breeze.in/session/start", "method": "POST", "type": "call"},
        {"name": "Jockey OTP", "url": "https://www.jockey.in/apps/jotp/api/login/send-otp/", "method": "POST", "type": "call"},
        {"name": "PW Live OTP", "url": "https://api.penpencil.co/v1/users/register/5eb393ee95fab7468a79d189?smsType=0", "method": "POST", "type": "call"},
        {"name": "Zoho Store OTP", "url": "https://store.zoho.com/api/v1/partner/affiliate/sendotp", "method": "POST", "type": "call"},
        {"name": "Aditya Birla OTP", "url": "https://udyogplus.adityabirlacapital.com/api/msme/Form/GenerateOTP", "method": "POST", "type": "call"},
        {"name": "Muthoot Finance OTP", "url": "https://www.muthootfinance.com/smsapi.php", "method": "POST", "type": "call"},
        {"name": "GoPaySense OTP", "url": "https://api.gopaysense.com/users/otp", "method": "POST", "type": "call"},
        {"name": "IIFL OTP", "url": "https://www.iifl.com/personal-loans", "method": "POST", "type": "call"},
        {"name": "BankOpen OTP", "url": "https://v2-api.bankopen.co/users/register/otp", "method": "POST", "type": "call"},
        {"name": "Tata Capital Retail OTP", "url": "https://retailonline.tatacapital.com/web/api/shaft/nli-otp/shaft-generate-otp/partner", "method": "POST", "type": "call"},
        {"name": "TradeIndia OTP", "url": "https://apis.tradeindia.com/app_login_api/login_app", "method": "POST", "type": "call"},
        {"name": "Orange Health OTP", "url": "https://accounts.orangehealth.in/api/v1/user/otp/generate/", "method": "POST", "type": "call"},
        {"name": "Jobhai OTP", "url": "https://api.jobhai.com/auth/jobseeker/v3/send_otp", "method": "POST", "type": "call"},
        {"name": "Mconnect OTP", "url": "https://mconnect.isteer.co/mconnect/login", "method": "POST", "type": "call"},
        {"name": "AstroSage Varta OTP", "url": "https://varta.astrosage.com/sdk/registerAS", "method": "POST", "type": "call"},
        {"name": "Spinny OTP", "url": "https://api.spinny.com/api/c/user/otp-request/v3/", "method": "POST", "type": "call"},
        {"name": "Dream11 OTP", "url": "https://www.dream11.com/auth/passwordless/init", "method": "POST", "type": "call"},
        {"name": "CityMall OTP", "url": "https://citymall.live/api/cl-user/auth/get-otp", "method": "POST", "type": "call"},
        {"name": "Bella Vita OTP", "url": "https://api.codfirm.in/api/customers/login/otp", "method": "POST", "type": "call"},
        {"name": "Oyo OTP", "url": "https://www.oyorooms.com/api/pwa/generateotp?locale=en", "method": "POST", "type": "call"},
        {"name": "Myma OTP", "url": "https://portal.myma.in/custom-api/auth/generateotp", "method": "POST", "type": "call"},
        {"name": "Freedo Rentals OTP", "url": "https://api.freedo.rentals/customer/sendOtpForSignUp", "method": "POST", "type": "call"},
        {"name": "Licious OTP", "url": "https://www.licious.in/api/login/signup", "method": "POST", "type": "call"},
        {"name": "Cosmofeed OTP", "url": "https://prod.api.cosmofeed.com/api/user/authenticate", "method": "POST", "type": "call"},
        {"name": "Bisleri OTP", "url": "https://apis.bisleri.com/send-otp", "method": "POST", "type": "call"},
        {"name": "Evital OTP", "url": "https://www.evitalrx.in:4000/v3/login/signup_sendotp", "method": "POST", "type": "call"},
        {"name": "QuickRide OTP", "url": "https://pwa.getquickride.com/rideMgmt/probableuser/create/new", "method": "POST", "type": "call"},
        {"name": "Clovia OTP", "url": "https://www.clovia.com/api/v4/signup/check-existing-user/", "method": "GET", "type": "call"},
        {"name": "Kwikfix OTP", "url": "https://admin.kwikfixauto.in/api/auth/signupotp/", "method": "POST", "type": "call"},
        {"name": "Brevistay OTP", "url": "https://www.brevistay.com/cst/app-api/login", "method": "POST", "type": "call"},
        {"name": "Hourly Rooms OTP", "url": "https://web-api.hourlyrooms.co.in/api/signup/sendphoneotp", "method": "POST", "type": "call"},
        {"name": "Madras Mandi OTP", "url": "https://api.madrasmandi.in/api/v1/auth/otp", "method": "POST", "type": "call"},
        {"name": "Bharat Loan OTP", "url": "https://www.bharatloan.com/login-sbm", "method": "POST", "type": "call"},
        {"name": "Pagarbook OTP", "url": "https://api.pagarbook.com/api/v5/auth/otp/request", "method": "POST", "type": "call"},
        {"name": "Vahak OTP", "url": "https://api.vahak.in/v1/u/o_w", "method": "POST", "type": "call"},
        {"name": "Redcliffe Labs OTP", "url": "https://api.redcliffelabs.com/api/v1/notification/send_otp/", "method": "POST", "type": "call"},
        {"name": "Ixigo OTP", "url": "https://www.ixigo.com/api/v5/oauth/dual/mobile/send-otp", "method": "POST", "type": "call"},
        {"name": "55Club OTP", "url": "https://api.55clubapi.com/api/webapi/SmsVerifyCode", "method": "POST", "type": "call"},
        {"name": "Zerodha OTP", "url": "https://zerodha.com/account/registration.php", "method": "POST", "type": "call"},
        {"name": "Testbook OTP", "url": "https://api.testbook.com/api/v2/mobile/signup", "method": "POST", "type": "call"},
        {"name": "Medibuddy OTP", "url": "https://loginprod.medibuddy.in/unified-login/user/register", "method": "POST", "type": "call"},
        {"name": "TradeIndia Reg OTP", "url": "https://api.tradeindia.com/home/registration/", "method": "POST", "type": "call"},
        {"name": "Beyoung OTP", "url": "https://www.beyoung.in/api/sendOtp.json", "method": "POST", "type": "call"},
        {"name": "Wrogn OTP", "url": "https://omqkhavcch.execute-api.ap-south-1.amazonaws.com/simplyotplogin/v5/otp", "method": "POST", "type": "call"},
        {"name": "Medkart OTP", "url": "https://app.medkart.in/api/v1/auth/requestOTP", "method": "POST", "type": "call"},
        {"name": "Coverfox OTP", "url": "https://www.coverfox.com/otp/send/", "method": "POST", "type": "call"},
        {"name": "Wooden Street OTP", "url": "https://www.woodenstreet.com/index.php?route=account/forgotten_popup", "method": "POST", "type": "call"},
        {"name": "GoMechanic OTP", "url": "https://gomechanic.app/api/v2/send_otp", "method": "POST", "type": "call"},
        {"name": "Lovelocal OTP", "url": "https://homedeliverybackend.mpaani.com/auth/send-otp", "method": "POST", "type": "call"},
        {"name": "Tyreplex OTP", "url": "https://www.tyreplex.com/includes/ajax/gfend.php", "method": "POST", "type": "call"},
        {"name": "Udaan OTP", "url": "https://auth.udaan.com/api/otp/send?client_id=udaan-v2", "method": "POST", "type": "call"},
        {"name": "Xylem OTP", "url": "https://xylem-api.penpencil.co/v1/users/register/64254d66be2a390018e6d348", "method": "POST", "type": "call"},
        {"name": "NoBroker V1 OTP", "url": "https://www.nobroker.in/api/v1/account/user/otp/send?otpM=true", "method": "POST", "type": "call"},
        {"name": "Vidyakul OTP", "url": "https://vidyakul.com/signup-otp/send", "method": "POST", "type": "call"},
        {"name": "WoodenStreet Register", "url": "https://api.woodenstreet.com/api/v1/register", "method": "POST", "type": "call"},
    ],
    "mix": []  # Will be auto-filled
}

# Auto-fill MIX APIs = SMS + CALL
APIS["mix"] = APIS["sms"] + APIS["call"]